name: whatcolors
description: "The easiest way to find out what colors are in a picture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  palette_generator: ^0.3.3+7
  image_picker: ^1.1.2
  provider: ^6.1.5
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.4
  clipboard: ^0.1.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  flutter_gen: ^5.10.0


flutter:

  uses-material-design: true

  assets:
    - assets/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
